<?php
/**
 * This file is part of the FIREGENTO project.
 *
 * FireGento_Core is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://www.firegento.com). All rights served.
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */
?>
<?php
/**
 * @var $this FireGento_Customer_Block_Password
 */
?>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function () {
        var validator = Validation.methods['validate-password'];
        validator.test = function(v) {
            // strip leading and trailing spaces
            var pass = v.strip();

            // Check length
            return !(pass.length>0 && pass.length <= <?php echo $this->getMinimumPasswordLength()?>);
        };

        var errorMsg = 'Please enter %d or more characters. Leading or trailing spaces will be ignored.';
        errorMsg = Translator.translate(errorMsg);
        errorMsg = errorMsg.replace('%d', <?php echo $this->getMinimumPasswordLength()?>);
        validator.error = errorMsg;
    });
//]]>
</script>
